#!/usr/bin/env bash

composer install
cp ./.env.example ./.env
php artisan key:generate
./BUILD
mkdir -p storage/framework/sessions
mkdir -p storage/framework/views
mkdir -p storage/framework/cache
mkdir -p bootstrap/cache
