#!/usr/bin/env bash
mkdir -p storage/framework/sessions
mkdir -p storage/framework/views
mkdir -p storage/framework/cache
mkdir -p bootstrap/cache

composer install
cp ./.env.example ./.env
php artisan key:generate
./node_modules/pb-application-scripts/BUILD
